'''*************************************************
content     generate_report

version     0.0.1
date   		26-12-2025

author      Harry Shaper <harryshaper@gmail.com>

*************************************************'''
import os
import yaml
import getpass
from datetime import datetime

#Creates the YAML report 
def generate_report(shoot_path): 
    shoot_day = shoot_path.split("\\")[-1]
    slate_list = [
        item for item in os.listdir(shoot_path)
        if os.path.isdir(os.path.join(shoot_path,item))
    ]
    setup_count = len(slate_list)
    
    report_file_name = shoot_day + "_report.yaml"
    report_path = os.path.join(shoot_path, report_file_name)

    #*********************************************************************#
    #Size checker
    #*********************************************************************#
    def get_folder_size(folder_path):
        total_bytes = 0
        for root, dirs, files in os.walk(folder_path):
            for file in files:
                total_bytes += os.path.getsize(os.path.join(root, file))
        return total_bytes

    total_bytes = get_folder_size(shoot_path)
    total_mb = total_bytes / (1024 * 1024)
    total_gb = total_mb / 1024

    # --- Get current date/time ---
    timestamp = datetime.now().strftime("%Y-%m-%d @ %H:%M")

    # Get current user
    user_name = getpass.getuser()
    
    with open(report_path, "w") as f:
        # Header
        f.write(f"{shoot_day}:\n")  #Shoot Day
        f.write(f"  setup_count: {setup_count}\n")  #Indented nicely
        f.write(f"  #------------------------------------------------#\n\n") #Line break

        # Loop over all slates
        for slate in slate_list:
            slate_path = os.path.join(shoot_path, slate)
            f.write(f"  Slate: {slate}:\n")  #Indented Slate heading
            
            for datatype in os.listdir(slate_path):
                datatype_path = os.path.join(slate_path, datatype)
                
                if os.path.isdir(datatype_path):  #Only count folders
                    datatype_count = len([
                        item for item in os.listdir(datatype_path)
                        if os.path.isdir(os.path.join(datatype_path, item))
                    ])
                    f.write(f"    {datatype}: {datatype_count}\n")  #Extra indentation for datatype
            
            f.write("\n")  #Blank line after each slate

        # --- Total captured size at the bottom ---
        f.write(f"  Total captured size: {total_gb:.2f} GB ({total_mb:.1f} MB)\n")
        f.write(f"  Report generated by: {user_name}\n")
        f.write(f"  Report generated: {timestamp}\n")
